cplay: handle IndexError in keymap.process
Hit this by pressing Shift+up on an ancient machine:
Traceback (most recent call last):
  if self.methods[key] is None: return 0
IndexError: list index out of range